version: "{build}"
image: Visual Studio 2017

build:
  verbosity: detailed

environment:
  matrix:
  - JAVA_HOME: C:/Program Files/Java/jdk1.8.0
#  - JAVA_HOME: C:\Program Files\Java\jdk9
#  - JAVA_HOME: C:\Program Files\Java\jdk10
#  - JAVA_HOME: C:\Program Files\Java\jdk11

install:
- cmd: echo JAVA_HOME = %JAVA_HOME%
- cmd: echo PATH = %PATH%

build_script:
- mvnw.cmd -B clean verify

on_failure:
- echo '================================== SUREFIRE OUTPUT =================================='
- cat **/target/surefire-reports/*.txt



