language: java
sudo: false
dist: trusty

os:
- linux
#- osx

jdk:
- oraclejdk8
#- openjdk9
#- openjdk10
#- openjdk11

script:
- echo PATH = ${PATH}
- echo JAVA_HOME = ${JAVA_HOME}
- java -version
- ./mvnw -B clean verify

after_failure:
- echo '================================== OUTPUT =================================='
- cat **/target/surefire-reports/*.txt

