language: java

services:
  - mysql

before_script:
  - mysql -utravis < src/main/resources/database/schema_creation.sql
  - mysql -utravis < src/main/resources/database/user.sql
  - mvn exec:java -Dexec.mainClass="org.hsqldb.Server" -Dexec.args="-database.0 file:target/data/inscripcion" &