language: java
sudo: false
jdk:
  - oraclejdk8
#notifications:
#  email: false
#script:
#  - mvn test -Droot.logging.level=INFO
#after_success:
#  - mvn jacoco:report coveralls:report -Droot.logging.level=INFO
