language: java

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8

install: mvn install -Dgpg.skip=true -DskipTests -Ddeployment.security.TLSv1=false -Ddeployment.security.TLSv1.1=true -Ddeployment.security.TLSv1.2=true -Dhttps.protocols=TLSv1.1,TLSv1.2
