language: java
sudo: false # faster builds

env:
    global:
        - TMPDIR=/tmp

script: 
    - mvn clean validate test failsafe:integration-test

after_success:
    - mvn clean package

bebore_deploy:
    - git config --local user.name "Caiwan"
    - git config --local user.email "caiwan.lupus@gmail.com"
    - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
    provider: releases
    api_key: "$GH_TOKEN"
    file: "target/cai-xls-utils.jar"
    skip_cleanup: true
    on:
        tags: true

