language: java
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
env: # important!
script:
- set -e
- mvn -q clean verify -B $TEST_PROFILE
matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk8
      env: TEST_PROFILE="-PtestNativeTransport"
    - jdk: oraclejdk8
      env: TEST_PROFILE="-PtestDomainSockets"
    - jdk: openjdk11
#notifications:
#  email:
#    recipients:
#      - julien@julienviet.com
#    on_success: always
#    on_failure: always
