language: java
jdk:
- oraclejdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key: "9ff8d3ea-3e4f-4f87-9d73-4d37b7baffab"
#    secure: "9ff8d3ea-3e4f-4f87-9d73-4d37b7baffab"
  app:
    nameless-hamlet-92047
