language: java
#notifications:
#  slack: mishima-group:8zsPeLEBTdLyT7kCZdQzIx4c
#deploy:
#  provider: heroku
#  app: twiliocallhandler
#  api_key:
#    secure: qcDCIkH7Vt9PXPffxKt1YT4eUiq4F7KJQErHBxDAjRRJtQS8WLMIi6xdetlqIlGhKzSpOy5htLGP8CyXT5XIW2hNDRYdbnCgTPoVe1CRxq4d/aymzRg08KTgljFBFi9RAtwiSBWOpC0ttw/dQGMktR7bpfat0lGNbTuSYLX0e7tRiS6IPZJn0CuKVXQRs2uW7qKmKYX0KSCuvghelwa4aI+d7e+raw6iOy87uLo8tOAyag1JXlVjf9DhOk1oxTbZngRfuEfvRgltJmBxstd/NuZJ4U7ZCFxmBnC1VntZ9QvDZOqiTOXpYDJRoheaOCwzQA5QHbxa2CF1OK2EhwFGIU4Nl64YaOy6KSX78u7IGllU/hGB6lFczX9wDJycOiw9vhSKXEfbT5Po55WVj7qshlpDDWY01h8aCza2DGi0yO8hcaYuQTvCq7bOJPzW9OqlMvz06Vm0uY8GsqAD+yG6DphwJm3w4nQNQTEYB1KRzD+rwg/elfg0wwILowWLmlKgl1AGo9NJclxolCSon1YMIOWV/JL03PFjyd3RnQkW9Ar9kiiM5wMCNlQIWzrHUNqo6UOpbXt9GX0l7/gGfyhs4SDgFE+2GaKIN91BB8HeW9X27f3zSTqIKZPGREK3Ur1IUKzIgzvxeNlU605bCxOix15tcvd7vBssleBKEaF+3X4=
