language: java
sudo: false
dist: trusty

# build all branches
branches:
  only:
  - /.*/

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9
    - jdk: oraclejdk10

install:
  - mvn -version

script:
  - mvn clean package
