language: java
jdk:
- oraclejdk8
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
script:
- set -e
- mvn -q clean verify -B -Dtest=Http1xTLSTest
#notifications:
#  email:
#    recipients:
#      - julien@julienviet.com
#    on_success: always
#    on_failure: always
