jobs:
  include:
    - stage: build
      language: java
      services: mysql
    - stage: deploy
      language: generic
      provider: script
      script: skip
      services: docker
      before_install:
        - mvn install -P docker -DskipTests
        - docker-compose build web
      script: bash docker/deploy/push_master.sh
      on: 
        branch: master AND type = push
      script: bash docker/deploy/push_dev.sh
      on: 
        branch = dev AND type = push
stages:
  - build
  - name: deploy
    skip_cleanup: true
