language: java
jdk:
  - oraclejdk8
before_install:
  - chmod +x mvnw
services:
  - postgresql
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432  
