jobs:
  include:
    - stage: build
      language: java
      services: mysql
    - stage: deploy-master
      language: generic
      provider: script
      skip_cleanup: true
      script: skip
      services: docker
      before_install:
        - mvn install -P docker -DskipTests
        - docker-compose build web
      script: bash docker/deploy/deploy.sh latest
    - stage: deploy-dev
      language: generic
      provider: script
      skip_cleanup: true
      script: skip
      services: docker
      before_install:
        - mvn install -P docker -DskipTests
        - docker-compose build web
      script: bash docker/deploy/deploy.sh dev
stages:
  - build
  - name: deploy-master
    if: branch = master AND type = push
  - name: deploy-dev
    if: branch = dev AND type = push
