language: java
env:
  matrix:
    - TEST_PROFILE=""
    - TEST_PROFILE="-PtestNativeTransport"
    - TEST_PROFILE="-PtestDomainSockets"
jdk:
- oraclejdk8
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
script:
- set -e
- mvn -q clean verify -B $TEST_PROFILE
#notifications:
#  email:
#    recipients:
#      - julien@julienviet.com
#    on_success: always
#    on_failure: always
