language: java
jdk: oraclejdk8
#mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: true
script: 
  - cd CustomerManagement
  - mvn test -B
  - cd ../VehicleManagement
  - mvn test -B

cache:
  directories:
  - $HOME/.m2