language: java

env:
  global:
    - SONATYPE_USERNAME=ph@phloc.com
    - secure: "L5FGOEtDCu/Ar2bRSDjgNXnKVVCvChLeXwwrwRYj37bTeeKKsi8sE8Nq1H7Lwxs+SRuNOsL28DAoF3K95CLQDtHXktrg55ERMLKWvlX2h0CRKjSQ5hem8StmCkHFWvk8eMBp02uh/H7jPpGbzLcZk
6Ux2t/Hpdo3qQB07zFMaN6XONtQ3IO0T4J0NhgrU/If/gdCIM4vC2maa/kCiWTqx0mRgzLMBkoN43ryIHvdpjYUofviFxiHp4zDUvXA4cMx0S9/6cpAioHOOkUh5JY0DRuww+3vBsQZkzE+T/m8aKMaYUZq/wMi3
9/IcKIzg8NlvmKw2EBAcFhs1gUWXeK7zM7MTa8jD7DVi7sVwnun3g39iXFtO+w5D4ET/LS1D9LaTZPW3we+srq1MFv4YL7XggSILr2k7QFjFDM+BqucRGqEV+tHWgViL5s56h3Z/b3je2Ti/do7Qq2SWvj30w7B9
jQqMlSotoAZESRwFBjtkrwjNw5ZcpHyJxGs4GDNW3i8BR+RsY7n0nKEP8OGblpAG6xIgTf+HxfRxYErg2rHf5dgq32uU2mep6TBCPZBIjMUqZl/oHJA+0ApN1Uax6oIuNP8lJwjAFXUUIhoBwWLncvHSFP8VqUqM
+DFQougMyOWQ4XShYPDIJOnf0XBalUwaVlNGSak6zKDFXdFIswb3qI="

jdk:
  - oraclejdk8
  
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
  
cache:
  directories:
  - $HOME/.m2

after_success:
  - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
