language: java
sudo: false
script:
  - mvn clean install -Ptravis
jdk:
  - openjdk8
  - openjdk7
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn sonar:sonar -Ptravis
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -Ptravis
addons:
  sonarcloud:
    organization: "tango-controls"
    token:
      secure: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.m2/repository'