language: java
# Enable container-based infrastructure
# see http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2/repository
  - $HOME/.m2/wrapper
install:
- ./mvnw -version
script:
- ./mvnw clean install
- cd $HOME/build/srcdeps
- git clone https://github.com/ppalaga/srcdeps-maven.git
- cd srcdeps-maven
- git checkout -b 180603-hash
- ./mvnw clean install
