jobs:
  include:
    - stage: build
      services:
        - mysql
    - stage: deploy-master
      provider: script
      script: skip
      services:
        - docker
      before_install:
        - mvn install -P docker -DskipTests
        - docker-compose build web
      script: bash docker/deploy/push_master.sh
    - stage: deploy-dev
      provider: script
      script: skip
      services:
        - docker
      before_install:
        - mvn install -P docker -DskipTests
        - docker-compose build web
      script: bash docker/deploy/push_dev.sh
language: java
stages:
  - build
  - name: deploy-master
    if: |
      branch = master AND \
      type != pull_request \
      OR fork = false
  - name: deploy-dev
    if: |
      branch = dev AND \
      type != pull_request OR \
      fork = false
