os:
  - linux
  - osx
language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "dimyriy-github"
script:
  - mvn clean test jacoco:report sonar:sonar coveralls:report --activate-profiles sonar,coveralls
