language: java
install: mvn install -DskipTests=true --settings settings.xml
script: mvn versions:set -DnewVersion=1.0.${env.TRAVIS_BUILD_NUMBER}

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./before-deploy.sh
  - ./deploy.sh
