language: java
before_install : 
 - echo "Hello Qualitykiosk"
notifications :
    email :
    recipients :
                  jnagpalnov@gmail.com
                  nkjethani825@gmail.com
    on_failure : always
