language: java
jdk: oraclejdk8
cache:
  directories:
    - "$HOME/.m2/"

branches:
  only:
  - master
  - dev

deploy:
  provider: heroku
  api_key: 0246955f-7af3-4a31-b212-8ab21042e111
  app:
    master: vast-falls-34370

notifications:
  webhooks:
    urls:
      - https://api.telegram.org/bot619741622:AAFVa531uU4HRNJQsrp81fY29nVnBcM9UDI/sendMessage?chat_id=582152089&text=Built
    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always