language: java

matrix:
  include:
  - os: linux
    dist: xenial
    jdk: openjdk8
    addons:
      apt:
        packages:
        - gdal-bin
  - os: linux
    dist: xenial
    jdk: openjdk8
    addons:
      apt:
        sources:
        - ppa:ubuntugis/ppa
        packages:
        - gdal-bin
  - os: linux
    dist: xenial
    jdk: openjdk8
    addons:
      apt:
        sources:
        - ppa:ubuntugis/ubuntugis-unstable
        packages:
        - gdal-bin

notifications:
  email: false

install: true

script:
  - ogr2ogr --version
  - mvn clean package

cache:
  directories:
  - $HOME/.m2
