language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
- export TZ=Pacific/Noumea
- export LANG=fr_FR.UTF-8
- mvn clean
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test jacoco:report
after_success:
- mvn coveralls:report
before_deploy:
- export RELEASE_PKG_FILE=$(ls bilan-energie-web/target/*.war)
deploy:
  provider: releases
  api_key:
    secure: XKwvHxdikL8EVFHmOrmFDRBlazQv5035IMdVYKqMnjcgeWILzfgxZZurxmGwrpt1Srvs6qHaXX9SisWqjEy4vwY24XYr0KCot4oKjCIbT0rBmuD77htVY3216UrpC3jb4AffkF980k/IwNWTu6bNrao/RnDm+92aLqLE0+1d0xkCPX8/Ekgphp0RSEl1NmfHzzng774cVe/GocP5WMdtBC63Mk+NsPLh1oR/kTgFM3LqvLQO3/Qg8sRl/hqdzBE6Y5hp5JsJk7YLz+ibTXwLz5egIudZ8DWf1a+XjOjwO7+oCG21MToeMBUG+PqryIdFuAvik75vGMVlbjIy+eZWcgeDy+bUL/UULCG3xVijhkN/jeAH1Y4Gz7xbHU7bb3w3XCzWc1GXorYl5mzx9LCbfv8YK95iIiN8cvc+9PFTEf4Ev4+D5e/ZL0Of9b81wTtRQ4g6xr45iy8Y6CvYu0cpfRShTLFQrcIwVQKHgwyqkRnVkaiJDQ3/1oHq0KkRZjR8dE7zWFeCN9DeqUYldLNYc5n5MB3pGVHtTsJwuFuw1SbEbCtVanuEjF94gtfJl6Op2qp7lYT/FiH88gE252YgrbjId14Zuifjd1d1MyX5jkORzb1x5sb1/cdSBVHlpRqbUUCJtX+B1jg3B8WEhhG8TF4zvyvWxejzVzIaiKT2t1Q=
  file:
  - ${RELEASE_PKG_FILE}
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/bilan-energie
notifications:
  slack:
    secure: mEEyS2dKPZ9wa7iQzRii6+LzsbFRZNO5RQWCEf96tMSwVmp2fpR8WU0WYiTQ0QEhQUpEakY7cMlk5JNUVvK2G+sASsmGQ2BooKlF7WdnaQh+ERgZlYyz/AuT6+w1Q9BMHQWF7DKZljWQsEpi/Ss51mpVRgxNmbLau2zlnolXXrU20YA+70cHTQGPHb8wbfuge6sl5ZCVa8V742Ql5VsSOiAchebFHoRDgNHu+NIqpU2HMGT7jJrI7lAdZm+GaK+OWCo11Z0rGdNw0ywCCgMZZo2a8zloblPFeBWZIcVynEOBM/wsB4mEavhxe4cApnfG7zco5s4aUV2MYG2b1K8IvdeDQ6QOoAcjGHDC/RChAcCXmv4jhB+0pWaYZ044JgYne9zDevDfvH2GL4BxrGxt3xAx+1Bhn6CXraC/mxzy07skujUAQ4T1gV2Jqv2u6Z00JlJuNJj33vAqEyxSGabm4p/izX+IiaYEVVrT9gOHQSDHuwEnxwFJxKoYCl5EndAwvaSDuDFl/r/rtot2BYuyNRvHSHMwG00FQK15mXPFI8HQcyPEptlL151koT5KsYk9tGKh8m1jvr5TE5Oi6dp9o7sgN5AM5eZGu5AOfX+nXxzXECA83Az+JcATBd/cDVzPuF5bKkI0bErsZvxBF7FzQUvf288qnw1BzuCZ0K3aOZM=
