language: java

jdk:
  - oraclejdk8
  
notifications:
  email:
    recipients:
      - chengwu@tencent.com
    on_success: always # default: change
    on_failure: always # default: always
  
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true

script: travis_wait 90 mvn test
