language: java
cache:
  directories:
  - .autoconf
  - $HOME/.m2
sudo: true
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_a65ab4f4a956_key -iv $encrypted_a65ab4f4a956_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- chmod +x ./mvnw
script:
- ./mvnw test -B
addons:
  ssh_known_hosts: 193.112.205.181
after_success:
- ssh root@193.112.205.181 "sh /cjyong/project/script/pc.sh"
notifications:
  email:
    recipients:
    - 2686600303@qq.com
    on_success: always
    on_failure: always
