ignore:
  - "src/main/java/com/brave/tradebravely/aop/logging"
  - "src/main/java/com/brave/tradebravely/config"
  - "src/main/java/com/brave/tradebravely/domain"
  - "src/main/java/com/brave/tradebravely/domain/esi"
  - "src/main/java/com/brave/tradebravely/repository"
  - "src/test/**/*"
