hub:
  image: selenium/hub:3.14
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox:3.14
  links:
    - hub
additionalFirefox:
  image: selenium/node-firefox:3.14
  links:
    - hub
chrome:
  image: selenium/node-chrome:3.14
  links:
    - hub
additionalChrome:
  image: selenium/node-chrome:3.14
  links:
    - hub
