server:
  port: 9292
  ssl:
    key-store: classpath:cjyong.jks
    key-store-password: cai123nb
    key-alias: cjyong
    enabled: true
  max-http-header-size: 8192
  compression:
    min-response-size: 512
    enabled: true
    mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg

logging:
  config: classpath:log4j2.xml

spring:
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    open-in-view: true
  mail:
    host: smtp.163.com
    username: 18375637632@163.com
    password: cai123nb
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          starttls:
            enable: true
            required: true


cpconfig:
  deploy-url: http://www.cjyong.com
  jwt:
    key: sh@?aku$#&!><?SD*o349()?/,<>+
    life: 7200000
  datasource:
    role: com.alibaba.druid.pool.DruidDataSource
    name: cjyong
    password: cjyong
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://193.112.205.181:3306/cp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    sql-script-encoding: UTF-8
    druid:
      max-active: 10
      initial-size: 3
      min-idle: 3
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statement: true
      max-pool-prepared-statement-per-connection-size: 20
  qiniu:
    access-key: aPNC2ZPghf8z4vCsYKu65dIIoG1IHdc7KQcbW_ei
    secret-key: _2CK5LNJUruidrT_IG6qUh2zCgXTKgchx4MKTmnB
    bucket: personalspace
    image-url: images.cjyong.com


