server:
  contextPath: /
  port: 80
  max-http-header-size: 8192
  compression:
    min-response-size: 512
    enabled: true
    mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
  tomcat:
    maxThreads: 10
    minSpareThreads: 3
    accesslog:
      directory: /usr/local/logger/springboot/cp/server.log
      pattern: combined
      enabled: true
  ssl:
          key-store: classpath:cjyong.keystore
          key-store-password: lasdfqwerfaw
          key-password: aoiwerngasfasd
          keyAlias: cjyong
          enabled: true

logging:
  config: classpath:log4j2.xml

spring:
  datasource:
        role: com.alibaba.druid.pool.DruidDataSource
        name: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://120.77.219.167:3306/cp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
        initialize: true
        sql-script-encoding: UTF-8
        druid:
          max-active: 10
          initial-size: 3
          min-idle: 3
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          poolPreparedStatement: true
          maxPoolPreparedStatementPerConnectionSize: 20
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
  mail:
    host: smtp.163.com
    username: 18375637632@163.com
    password: cai123nb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

apiInfo:
  deployurl: https://www.cjyong.com
  jwt:
      key: shaku$#&!><?SD*o349()?/,<>+
      life: 7200000

qiniu:
  accessKey: aPNC2ZPghf8z4vCsYKu65dIIoG1IHdc7KQcbW_ei
  secretKey: _2CK5LNJUruidrT_IG6qUh2zCgXTKgchx4MKTmnB
  bucket: personalspace
  baseUrl: p062e4r83.bkt.clouddn.com


