---
logging:
  file: structure.log
  level:
    org:
      springframework:
        security: INFO
        web: INFO
  path:
---
server:
  port: 9000
---
spring:
  data.rest:
    returnBodyOnCreate: true
    returnBodyOnUpdate: true
  datasource:
    platform: h2
    url: jdbc:h2:./h2;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: structure
    password: structure
  h2:
    console:
      enabled: true
      path: /h2console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: create-drop
    open-in-view: true
    show-sql: false
  profiles:
    active: default
  redis:
    host: localhost 
    password:
    port: 6379
  session:
    store-type: redis
    timeout: 3600
---
facade.url: http://localhost:4200
---
structure:
  model:
    packages:
      - tech.spring.structure.model
      - tech.spring.structure.auth.model
  password.duration: 365
  whitelist: 0:0:0:0:0:0:0:1
