server: 
  port: 11111

spring:
  rabbitmq:
    host: rabbit
  cloud:
    stream:
# no content-type:json here. the message is sent from logstash where headers cannot be set
      default:
        contentType: null
      bindings:
        enrichment:
          group: money
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: es:9300 

logstash:
  host: logstash-service
  port: 4560

logging: 
  level.guru.bonacci.spectre.money: INFO


