server:
  port: 5000
  servlet:
    context-path: /auth

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/auth/users/current
  h2.console.enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

logstash:
  host: logstash-service
  port: 4560

logging: 
  level:
    org.springframework.security: INFO
    guru.bonacci.oogway.auth: INFO