apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  selector:
    component: elasticsearch
    role: data
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
  type: NodePort