apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:5.5.3
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_URL
          value: http://es:9200
        - name: xpack.security.enabled
          value: "false"
---
kind: Service
apiVersion: v1
metadata:
  name: kibana-service
spec:
  selector:
    app: kibana
  ports:
  - protocol: TCP
    port: 5601
  type: LoadBalancer
