server: 
  port: 3333
  servlet:
    context-path: /doors

spring:
  rabbitmq:
    host: rabbit
  cloud:
    stream:
      default:
        contentType: application/json
        binder: rabbit
      rabbit:
        bindings:
          spectre:
            producer:
              exchangeType: direct
              routingKeyExpression: '''eavesdrop'''

service:  
  lumberjack:
    enabled: false
    name: lumberjack-service
    url: http://lumberjack-service:11235
  oracle:
    enabled: false
    name: oracle-service
    url: http://oracle-service:4444
  auth:
    name: auth-service
    url: http://auth-service:5000
  spectre:
    enabled: true

security:
  oauth2:
    client:
      clientId: doorway-service
      clientSecret: doorway-service-secret
      accessTokenUri: http://auth-service:5000/auth/oauth/token
      scope: resource-server-read

logstash:
  host: logstash-service
  port: 4560
      
logging: 
  level: 
    root: WARN
    org.springframework: INFO
    guru.bonacci.oogway.doorway: INFO


file.name.answers.to.win.time: answers-to-win-time.txt 