server: 
  port: 4444
  servlet:
    context-path: /oracle

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/auth/users/current

spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: es:9300 

logstash:
  host: logstash-service
  port: 4560
    
logging: 
  level.guru.bonacci.oogway.oracle: DEBUG