server:
  port: 11235
  servlet:
    context-path: /lumber

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/auth/users/current

spring:
  data:
    mongodb:
      host: mongodb-service
      database: admin
      port: 27017
      username: main_admin
      password: abc123

logstash:
  host: logstash-service
  port: 4560

logging: 
  level.guru.bonacci.oogway.lumberjack: INFO  