# local/default
custom:
  iiif:
    image:
      maxWidth: 65500
      maxHeight: 65500
      canonicalRedirect: true

info:
  app:
    encoding: 'UTF-8'
    java:
      source: '1.8'
      target: '1.8'
    project:
      name: 'DigitalCollections: Hymir IIIF Server'
      groupId: 'de.digitalcollections'
      artifactId: 'iiif-server-hymir'
      version: '3.6.0-SNAPSHOT'
      buildDetails: '3.6.0-SNAPSHOT manually built by root at 2018-05-29 14:09:37'

management:
  endpoints:
    web:
      base-path: '/monitoring'
      exposure:
        include: '*'
  server:
    port: 9001

server:
  port: 9000
  server-header: "DigitalCollections: Hymir IIIF Server v3.6.0-SNAPSHOT"

spring:
  messages:
    basename: messages,messages-overlay,messages-commons
  profiles:
    active: local
  security:
    user:
      name: admin
      password: secret
      roles: ACTUATOR
  thymeleaf:
    cache: false
    mode: HTML

---

# PROD
spring:
  profiles: PROD
  thymeleaf:
    cache: true